### PR TITLE
fix: updates jwx library to use its thread-safe jwks cache

### LINKED ISSUE #65: jwkCache can't be updated concurrently
Last night my service failed with this traceback:

```plaintext
fatal error: concurrent map writes
goroutine 20214 [running]:
github.com/passageidentity/passage-go.(*App).fetchJWKS(0xc00017a390)
	/opt/render/project/go/pkg/mod/github.com/passageidentity/passage-go@v1.11.0/authentication.go:70 +0xb8
github.com/passageidentity/passage-go.New({0xc00003a33f, 0x18}, 0x0?)
	/opt/render/project/go/pkg/mod/github.com/passageidentity/passage-go@v1.11.0/app.go:41 +0x185
       <snip>
```

This is because fetchJWKS() is writing to the jwkCache without synchronization: https://github.com/passageidentity/passage-go/blob/main/authentication.go#L70C2-L70C10

I think one of these changes is needed:
* This code needs to be wrapped in a lock or mutex (the reads may need them as well)
* The jwkCache global (defined [here](https://github.com/passageidentity/passage-go/blob/main/app.go#L49)) needs to be converted to e.g. `sync.Map` or similar.
* The cache needs to be stored per-app instead of global
* The documentation needs to be updated to encourage users to create a single app instance (using e.g. OnceValue) instead of one per request.

Great product and service, BTW. Your dev experience blows the competition out of the water.

### PR DESCRIPTION
**Pull request by ctran88**
## What's New?

**Problem:**
Our jwks cache was a `map`, so it is not thread safe.

If the `passage.App` struct was being called via `passage.New` in multiple threads, i.e. it is being initialized per request thread in an API server, then it would throw a fatal "concurrent map writes" error.

**Solution:**
Use a thread-safe data structure to cache the jwks.

Our existing jwt/jwks library, https://github.com/lestrrat-go/jwx, has its own thread-safe (via RW mutex) caching implementation that we can make use of by upgrading from v1 to v2.

**Tests:**
Adding and running this test on `main` will fail because it detects a race condition (concurrent writes to the `jwkCache` map variable). It will pass on this branch
```
go test -race -run TestAppJWKSCacheWriteConcurrency

WARNING: DATA RACE
Write at 0x00c0000013a8 by goroutine 9:
  github.com/passageidentity/passage-go.(*App).fetchJWKS()
      /Users/christran/repos/passage-go/authentication.go:70 +0x100
  github.com/passageidentity/passage-go.New()
      /Users/christran/repos/passage-go/app.go:41 +0x208
  github.com/passageidentity/passage-go_test.TestAppJWKSCacheWriteConcurrency.func1()
      /Users/christran/repos/passage-go/app_test.go:54 +0x138

Previous write at 0x00c0000013a8 by goroutine 8:
  github.com/passageidentity/passage-go.(*App).fetchJWKS()
      /Users/christran/repos/passage-go/authentication.go:70 +0x100
  github.com/passageidentity/passage-go.New()
      /Users/christran/repos/passage-go/app.go:41 +0x208
  github.com/passageidentity/passage-go_test.TestAppJWKSCacheWriteConcurrency.func1()
      /Users/christran/repos/passage-go/app_test.go:54 +0x138

Goroutine 9 (running) created at:
  github.com/passageidentity/passage-go_test.TestAppJWKSCacheWriteConcurrency()
      /Users/christran/repos/passage-go/app_test.go:51 +0x5c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40

Goroutine 8 (finished) created at:
  github.com/passageidentity/passage-go_test.TestAppJWKSCacheWriteConcurrency()
      /Users/christran/repos/passage-go/app_test.go:51 +0x5c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1689 +0x180
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1742 +0x40
==================
--- FAIL: TestAppJWKSCacheWriteConcurrency (0.20s)
    testing.go:1398: race detected during execution of test
FAIL
exit status 1
FAIL	github.com/passageidentity/passage-go	0.812s
```
https://github.com/passageidentity/passage-go/blob/795b803deebec07314bb7176c4e3c0225fd94ff6/app_test.go#L52-L70

**References:**
- jwk.Cache [example](https://github.com/lestrrat-go/jwx/blob/v2/docs/04-jwk.md#auto-refreshing-remote-keys)
- jwk.Cache [definition](https://github.com/lestrrat-go/jwx/blob/v2/jwk/cache.go#L84)
- jwk.Cache's [underlying cache store](https://github.com/lestrrat-go/httprc/blob/v1.0.6/cache.go#L30)

## Screenshots (if appropriate):

Please attach any screenshots that would help illustrate the changes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have manually tested my code thoroughly
- [ ] I have added/updated inline documentation for public facing interfaces if relevant
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing integration and unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Additional context

Add any other context or screenshots about the pull request here.

### CODE REVIEW

File: app.go [hunk 1]
```diff
@@ -2,20 +2,24 @@ package passage
...
 type App struct {
-	ID     string
-	JWKS   jwkLibrary.Set
-	Config *Config
-	client *ClientWithResponses
+	ID        string
+	JWKS      jwk.Set
+	Config    *Config
+	client    *ClientWithResponses
+	jwksCache *jwk.Cache
```
Comment (bertrmz) [inline app.go:22]: It looks like this is using 2 data structures (`jwk.Set` and `jwk.Cache`) to store jwk info.

Would it be possible to use [jwk.CachedSet](https://github.com/lestrrat-go/jwx/blob/8d1d78351e9f259723f9f558889a78e327379683/examples/jwk_cached_set_example_test.go#L27) & store it in 1?

Comment (ctran88) [reply app.go:22]: I tried it at first. It's a slim immutable shim over Set. But the blocker was that it didn't allow access to the underlying cache, which is needed to perform the refresh.

Comment (bertrmz) [reply app.go:22]: It looks like the structure abstracts away the need to refresh manually (in the doc [here](https://github.com/lestrrat-go/jwx/blob/develop/v3/docs/04-jwk.md#auto-refreshing-remote-keys)), though that'd require some other refactoring.

& it's not necessary to solve the thread-safe issue, so we can keep this change focused on the fix.

File: app.go [hunk 2]
```diff
@@ -38,16 +42,17 @@ func New(appID string, config *Config) (*App, error) {
 		client: client,
 	}
 
-	app.JWKS, err = app.fetchJWKS()
-	if err != nil {
+	// cached set setup taken from https://github.com/lestrrat-go/jwx/blob/8d1d78351e9f259723f9f558889a78e327379683/examples/jwk_cache_example_test.go#L21-L36
```
Comment (bertrmz) [inline app.go]: This link can perhaps be omitted, as the example is surfaced in the package's docs [here](https://github.com/lestrrat-go/jwx/blob/develop/v3/docs/04-jwk.md#auto-refreshing-remote-keys).

But I'm also good with keeping it if it feels like a good point of reference.

File: app.go (hunk 1 above)
Comment (ctran88) [reply app.go:22]: it was originally required to fulfill the manual re-fetch logic https://github.com/passageidentity/passage-go/blob/8cb184a60bcced14821b84fad7ae2507a4abe85b/authentication.go#L45-L55

but given our recent discussions around dropping it, it can be refactored to use the `CachedSet` instead. though i wanted to tackle removing the re-fetch logic in a separate PR since it's a functional change.

**Review by bertrmz — APPROVED** [review]

File: app.go (hunk 2 above)
Comment (ctran88) [reply app.go]: removed in [058e8d4](https://github.com/passageidentity/passage-go/pull/88/commits/058e8d4b47909b5cfc17d2f04faf7b43351443c0)
